import type { Metadata } from "next";
// This fonts will load on build time and we get it from server on app launch
// Place font in _next/static/css/...
// Without next/font we have to load fonts with <link> on app launch (Additional HTTP requests, FOIT, FOUT)
import { Geist_Mono, Public_Sans } from "next/font/google";
import "./globals.css";
import NotificationBanner from "@/components/notification-banner/notification-banner";

// ! Need to replace with Public_Sans font - Tailwind CSS default fonts. It is done in global.css

// Main font for all text in app
// Public_Sans({}) - load font, create it own variable --font-public-sans
// ${publicSans.variable} - will add CSS class that install font-family: var(--font-public-sans) on body
const publicSans = Public_Sans({
  variable: "--font-public-sans",
  subsets: ["latin"],
  weight: "variable", // full range of weights from 100 to 900
  style: ["normal", "italic"],
  display: "swap",
});

// Monospace font - for code blocks, logs, tables (<pre>, <code>, font-mono from Tailwind CSS)
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${publicSans.variable} ${geistMono.variable} antialiased`}
      >
        <NotificationBanner />
        {children}
      </body>
    </html>
  );
}
